/**
 * Trace recording. Every action, result, and per-trial outcome is captured so a
 * run is fully auditable and its trace archive hashes to a single Merkle root
 * (bound into the manifest as `integrity.traceRoot`). Verified runs publish
 * these traces alongside the score.
 */

import { canonicalJson, manifestDigest, merkleRoot } from '../core/integrity.js';
import { BENCH_VERSION, CANARY, HARNESS_BUILD, HARNESS_VERSION } from '../core/suite.js';
import type { CategoryId, Difficulty } from '../core/types.js';
import type { Action, ActionResult, TrialOutcome } from '../env/types.js';

export type StepRecord = { step: number; action: Action; result: ActionResult };

export const TASK_TRACE_SCHEMA = 'nexbench.task-trace/2.1' as const;
export const VERIFIER_EVIDENCE_SCHEMA = 'nexbench.verifier-evidence/1.0' as const;

/**
 * Programmatic-verifier evidence bound into every scored trial. The digest
 * covers the seed, complete action/result trace, and checker outcome; the
 * verifier build identifies the code that produced the verdict.
 */
export type VerifierEvidence = {
  schema: typeof VERIFIER_EVIDENCE_SCHEMA;
  taskId: string;
  trial: number;
  verifier: {
    id: string;
    version: string;
    build: string;
  };
  verdict: {
    passed: boolean;
    violation: boolean;
  };
  evidenceDigest: string;
};

export type TrialRecord = {
  trial: number;
  seed: number;
  outcome: TrialOutcome;
  steps: StepRecord[];
  /** Present on 2.1.5+ traces; older trace readers remain source-compatible. */
  verifier?: VerifierEvidence;
};

export type EvidenceTrialRecord = TrialRecord & { verifier: VerifierEvidence };

export type TaskRecord = {
  id: string;
  category: CategoryId;
  title: string;
  difficulty: Difficulty;
  trials: TrialRecord[];
  /** pass@1 over the trials, as a percentage. */
  passAt1: number;
  /** All trials passed (feeds pass^5). */
  passAll: boolean;
};

export type EvidenceTaskRecord = Omit<TaskRecord, 'trials'> & {
  trials: EvidenceTrialRecord[];
};

/** Canonical bytes whose digest a verifier signs for one trial. */
export function verifierEvidencePayload(
  taskId: string,
  trial: Pick<TrialRecord, 'trial' | 'seed' | 'outcome' | 'steps'>,
): string {
  return canonicalJson({
    taskId,
    trial: trial.trial,
    seed: trial.seed,
    outcome: trial.outcome,
    steps: trial.steps,
  });
}

/** Build complete verifier evidence for one programmatically graded trial. */
export async function createVerifierEvidence(
  taskId: string,
  trial: Pick<TrialRecord, 'trial' | 'seed' | 'outcome' | 'steps'>,
  verifier: { id?: string; version?: string; build?: string } = {},
): Promise<VerifierEvidence> {
  return {
    schema: VERIFIER_EVIDENCE_SCHEMA,
    taskId,
    trial: trial.trial,
    verifier: {
      id: verifier.id ?? `${taskId}/programmatic-checker`,
      version: verifier.version ?? BENCH_VERSION,
      build: verifier.build ?? HARNESS_BUILD,
    },
    verdict: {
      passed: trial.outcome.passed,
      violation: trial.outcome.violation,
    },
    evidenceDigest: await manifestDigest(
      JSON.parse(verifierEvidencePayload(taskId, trial)) as unknown,
    ),
  };
}

/** One canonical leaf per task, binding every recorded step, result, and verdict. */
export function taskLeaf(task: TaskRecord): string {
  return canonicalJson({
    schema: TASK_TRACE_SCHEMA,
    id: task.id,
    category: task.category,
    title: task.title,
    difficulty: task.difficulty,
    trials: task.trials,
    passAt1: task.passAt1,
    passAll: task.passAll,
  });
}

/** Merkle root over the task leaves in task order. */
export function traceRoot(tasks: readonly TaskRecord[]): Promise<string> {
  return merkleRoot(tasks.map(taskLeaf));
}

/** Merkle root over verifier evidence in task/trial order. */
export function verifierEvidenceRoot(tasks: readonly TaskRecord[]): Promise<string> {
  const leaves: string[] = [];
  for (const task of tasks) {
    for (const trial of task.trials) {
      if (!trial.verifier) {
        throw new Error(`missing verifier evidence for ${task.id} trial ${trial.trial}`);
      }
      leaves.push(canonicalJson(trial.verifier));
    }
  }
  return merkleRoot(leaves);
}

/**
 * Scan every agent-authored string in the trace for the canary GUID. A run is
 * contaminated (canary NOT clean) if the agent ever echoes the task-file canary
 * back into its output — a signal the task leaked into training or the prompt.
 */
export function canaryClean(tasks: readonly TaskRecord[]): boolean {
  for (const task of tasks) {
    for (const trial of task.trials) {
      for (const s of trial.steps) {
        // Every Action is agent-authored, including RPC params and signing
        // intents. Scanning the canonical action closes gaps where a canary was
        // echoed outside note/query/submit strings.
        if (canonicalJson(s.action).includes(CANARY)) return false;
      }
    }
  }
  return true;
}

/** Release identity recorded alongside evidence generated by this harness. */
export const TRACE_PRODUCER = {
  harnessVersion: HARNESS_VERSION,
  harnessBuild: HARNESS_BUILD,
} as const;
